name: 'Set monday.com Item State'
author: "PolygonSoftware"
branding:
  icon: 'hash'
  color: 'orange'
description: 'Set state of item on monday.com mentioned in a commit message or PR Title'
inputs:
  monday-token:
    description: 'API Access token for monday.com'
    required: true
  text:
    description: 'Text that includes the Item ID. Example for PR Title: github.event.pull_request.title'
    required: true
  status-column-title:
    description: 'Title of column of which status shall be updated'
    required: false
  status-column-id:
    description: 'ID of column of which status shall be updated'
    required: false
  prefix:
    description: 'String that must occur right before the item ID, like "#(" for fix(#1234567890)'
    required: false
  postfix:
    description: 'String that must occur right after the item ID, like ")" for fix(#1234567890)'
    required: false
  set-status:
    description: 'Item-Status text that shall be set'
    required: true
  require-status:
    description: 'Only change the status of the item if it currently has this status'
    required: false
  multiple:
    description: 'If multiple Item IDs are found, set status of all of them. Default: Only first found Item ID is used.'
    required: false
    default: 'false'
  monday-organization:
    description: 'Monday.com organization name - used to generate the directlinks in the action output message'
    required: false
  allow-no-item-id:
    description: 'Do not fail when no monday.com Item-ID is found'
    required: false
    default: 'false'
outputs:
  item-ids:
    description: "The monday.com item-ID that for which the status was set"
  message:
    description: "A markdown formatted text that informs about the mentioned items"
runs:
  using: "node12"
  main: "dist/index.js"
