name: Example - Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release new Live-Version
    runs-on: ubuntu-latest
    steps:
      - name: Update state of monday.com items
        uses: polygon-software/action-monday-state@main
        if: ${{ github.event.release.draft != 'true' }}
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ github.event.release.body }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'In LIVE'
