name: Example - PR Reviewed

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  set-status:
    name: Set monday.com Item Status
    runs-on: ubuntu-latest
    steps:
      # If PR was 'COMMENTED'
      - name: Update state of monday.com items
        uses: polygon-software/action-monday-state@main
        if: ${{ github.event.review.state == 'commented' }}
        with:
          allow-no-item-id: true
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ github.event.pull_request.title }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'Commented'

      # If PR was 'APPROVED'
      - name: Update state of monday.com items
        uses: polygon-software/action-monday-state@main
        if: ${{ github.event.review.state == 'approved' }}
        with:
          allow-no-item-id: true
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ github.event.pull_request.title }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'Commented'

      # If PR was 'REJECTED'
      - name: Update state of monday.com items
        uses: polygon-software/action-monday-state@main
        if: ${{ github.event.review.state == 'rejected' }}
        with:
          allow-no-item-id: true
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ github.event.pull_request.title }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'Commented'

