name: Example - Release Draft

on:
  push:
    tags:
      - "v*"

jobs:
  release-draft:
    name: Create Release Draft
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/changelog-configuration.json"

      # Set status on-prerelease for items that appear in a commit message into pre-release
      - name: Update state of monday.com items
        uses: polygon-software/action-monday-state@main
        id: monday-state
        with:
          allow-no-item-id: true
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          monday-organization: polygonsoftware
          text: ${{ steps.changelog.outputs.changelog }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'In TEST'

      - name: Archive Release
        uses: polygon-software/action-zip@master
        with:
          files: dist
          dest: release.zip

      - name: Upload release.zip
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: release.zip

      - name: Release
        uses: polygon-software/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release.zip
          body: |
            ${{ steps.changelog.outputs.changelog }}
            ---
            ${{ steps.monday-state.outputs.message }}
