name: Example - Push Dev

on:
  push:
    branches: [dev]

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      # Set status on-dev for items that appear in a commit message into DEV
      - name: Use own action to set status of item
        uses: polygon-software/action-monday-state@main
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ join(github.event.commits.*.message, ', ') }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'In DEV'

