name: Example - Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Set status on-prerelease for items that appear in a commit message into pre-release
      - name: Use own action to set status of item
        uses: polygon-software/action-monday-state@main
        id: monday-state
        continue-on-error: true
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          text: ${{ steps.changelog.outputs.changelog }}
          prefix: '#'
          status-column-id: 'status'
          set-status: 'In TEST'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: dist/index.js
          body: |
            ${{ steps.changelog.outputs.changelog }}
            ---
            ${{ steps.monday-state.outputs.message }}
